### ISSUE TITLE
Add refresh interval dropdown

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/gatus#1]
If the health of your services are checked every 5 minutes, there's no point refreshing the page every 10 seconds.

Therefore, a dropdown should be added for setting the refresh interval.

**Comment by hurnhu** [comment]
Hey I have something for this, all I need to do is test and tweak.

I'm fairly new to development in a docker box, so how would I build the images and include the changes i did in the static folder?
I built the docker images with docker build . and ran it wit docker run docker run -p 8080:8080

**Comment by TwinProduction** [comment]
Released in v1.1.1

**Comment by wahajahmed010** [comment]
probe

**Comment by wahajahmed010** [comment]
test

**Comment by wahajahmed010** [comment]
test

**Comment by wahajahmed010** [comment]
probe
