### ISSUE TITLE
Implement Postgres as a storage solution

### ISSUE THREAD

**Issue by fabjan** [TwinProduction/gatus#124]
I stumbled on this neat status page solution the other day and am trying it out, cool stuff!

I see Store is an interface, and that there is one implementation (in-memory cache with a file used to persist over restarts). However I think it's missing some way to persist the observed results which is more usable in a stateless container, where you don't want to write to a file system.

Is there perhaps already some extension out there that provides a Store backed by e.g. Redis or Postgres? I would not mind contributing, but if the effort had already been made then that would be unnecessary.

The point would not be to enable some high availability configuration (I think that would add quite a bit more synchronization work), but simply being able to restart or reconfigure gatus without losing the previous results would be nice.

Also, the auto save interval could be made configurable.

**Comment by TwinProduction** [comment]
Yes, Postgres as a storage is definitely something I'm planning on implementing at some point, which is why I added an interface for storage rather than just the implementation. 

Unfortunately, I haven't really had the time to work on that yet 😔

**Comment by fabjan** [comment]
Alright. Well if nothing is started yet I’ll fork and make an effort if I get some time in these next couple of weeks.

Unless you prefer otherwise, I like a PR with code to discuss. This seems like not too much to iron out ahead.

**Comment by TwinProduction** [comment]
@fabjan That works for me! I've got a busy few weeks ahead of me, but don't hesitate to ask if you have any questions and I'll try my best to answer them.

**Comment by fabjan** [comment]
So now is the first time I sat down to really go through the code, I just created the issue on a whim because this is a cool app and I thought it was missing persistence. I have not used it much, so bear with me if some questions are silly!

Work will be tracking here: https://github.com/fabjan/gatus/tree/feature/store-postgres

My current thinking is that core.ServiceStatus and core.Result are entities that can have their own tables.

We can "inline" the core.Event slice in the service status table, as well as the core.Uptime and map of core.HourlyUptimeStatistics. The events are small and few (at most 50 currently), the uptime data is also tiny and does not have a lot of elements (at most 240 currently). It seems to me like it would be a bit wasteful to treat them as entities.

The core.ConditionResult slice can be inlined in the result table, it doesn't seem like they are too huge or too many and they would also be weird to treat as entities.

I don't want to make things too complicated or add too many dependencies either, so will start out without any ORM library and see how complex it gets. I will need to learn a bit more about the arrays and structs and JSON support in Postgres.

I don't want to make this work too dependent on the multi-server/distribution discussion but I also don't want to contribute something that hinders that work. What are your thoughts on consistency? The current solution only really allows for one server, right? Every seven minutes it persists status information to the save file. I'll make sure different instances can use the same database without stomping over each other.

Regardless of if we have multiple writers with their own database connections and one "overlord" instance that frontends query through, or one primary backend that all secondary instances write their updates to, or multiple backends that all serve one frontend with multiple clients (I have not read too much of that discussion), I think the data must be slightly out of date any given moment in time unless no instance uses any in-memory caching and always query the same database. There seems to me to be little win in enforcing consistency and lots to lose in terms of latencies introduced when observing results. It will probably be alright to have a lag of several seconds between an observation happening and the UI being able to see it, but alerting might be different. How alerting will play with distribution is a discussion for those issues.

The auto save interval being configurable is perhaps enough to let users decide how timely they want their information.

**Comment by TwinProduction** [comment]
Hey @fabjan, for now, I'd say that you can completely ignore the multi-server issue; that's a completely different feature, and you shouldn't have to worry about it at all.

As for the idea you've had so far, I completely agree that having a table for core.ServiceStatus and a table for core.Result is sufficient.

Ultimately, the only operations that need to be supported are those in the storage provider interface, which should be answerable with what you suggested.

**Comment by TwinProduction** [comment]
Small update on this issue; I started working on adding support for SQLite, which might be fully backward compatible with Postgres.

**Comment by fabjan** [comment]
Cool stuff!

Sorry I’m not being very fast in my fork/branch, enjoying some summer time off.

**Comment by TwinProduction** [comment]
No problem @fabjan.

I actually looked at your fork prior to starting, just to prevent overlaps.

Enjoy your summer :)

**Comment by TwinProduction** [comment]
Unfortunately, some of my plans are forcing me to steal this task from you ;)
Hope you don't mind too much!

**Comment by fabjan** [comment]
Of course I don’t mind at all. Good stuff 👍

It seems I over estimated how much time I would spend coding in my free time after getting back to work.

**Comment by TwinProduction** [comment]
Released in [v3.1.0](https://github.com/TwinProduction/gatus/releases/tag/v3.1.0)
