### ISSUE TITLE
Redirection checks are not working

### ISSUE THREAD

**Issue by omederos** [TwinProduction/gatus#126]
First of all, thanks for such a simple tool and for making it open source :) I tried to see if the following issue was posted already, but I couldn't find anything.

All my 301 and 302 checks are failing, and it seems to be because when making the HTTP requests, it's following redirects by default.

Here's an example. https://inbox.google.com does a 301 to https://mail.google.com/, but the status code in the image below is 200.

Is this by design?

![image](https://user-images.githubusercontent.com/738291/124508849-a6ec3000-dd9e-11eb-8378-a980b7743968.png)

**Comment by TwinProduction** [comment]
Good catch, the fix for that is fairly simple.
I'm a little worried that some people are accepting this behavior as the "intended" behavior and have built their tests with that idea in mind 🤔

That said, I doubt it is the case, so I'll take the risk.

**Comment by TwinProduction** [comment]
@omederos Please let me know if this fixed it for you.

**Comment by omederos** [comment]
Hey @Twi

I completely missed this reply! I'll give it a try tomorrow but that should fix it.

Thank you!

**Comment by omederos** [comment]
Hey Chris,

I completely missed this reply! I'll give it a try tomorrow but that should fix it.

Thank you!

**Comment by TwinProduction** [comment]
Released in [v2.8.0](https://github.com/TwinProduction/gatus/releases/tag/v2.8.0)

**Comment by TheSpad** [comment]
I'm "that guy" who was doing some tests that expected redirects to work. I can probably rework them but it would be prefereable to have an option to follow redirects so I don't have to worry if the redirect destination changes.

**Comment by TwinProduction** [comment]
@TheSpad Thanks for letting me know.

I'll add a configuration to make this behavior configurable, and I'll revert the behavior to the previous default behavior, that way, you won't have anything to do on your end.

**Comment by TwinProduction** [comment]
@TheSpad could you try the latest version and let me know if it works for you by default (without any changes)?

@omederos As for you, unfortunately, you'll have to leverage the new feature to ignore redirects: https://github.com/TwinProduction/gatus#client-configuration

The reason why I decided to make that change when it was the new default was because evidently I was wrong when I assumed nobody was expecting redirects to happen by default.

In any case, as soon as both of you have given me the 👍, I'll release a new minor version of Gatus to set that in stone.

**Comment by TheSpad** [comment]
@TwinProduction I'll give it a test today but I need to spin up a new instance somewhere as I'm currently running on arm via docker and your `latest` tag only builds amd64.

**Comment by TheSpad** [comment]
It looks like with the latest (docker) build it's always following redirects even with
```yml
    client:
      ignore-follow: true
```

In my test case a `curl` from the same host confirms a `HTTP/2 301` response but the Gatus check is passing and the webui shows:
![image](https://user-images.githubusercontent.com/8425502/127664308-20fcdeb0-6fa8-48d1-bef8-122a10e7dbc9.png)

**Comment by TwinProduction** [comment]
I'll look into it again.

Also, I might rename ignore-follow to ignore-redirect; ignore-follow sounds weird.

**Comment by TwinProduction** [comment]
@TheSpad So it turns out that I had unconsciously already applied the change I mentioned.

The right parameter is `ignore-redirect`, not `ignore-follow`, but the documentation says `ignore-follow` 🤣 

I'll update the documentation.

**Comment by TheSpad** [comment]
@TwinProduction with `ignore-redirect: true` it now fails as expected on my test case and works correctly with redirects for everything using the default.

**Comment by TwinProduction** [comment]
@TheSpad Glad to hear that!

I'm closing the issue. Hopefully, this time is the right one 🤣

**Comment by TwinProduction** [comment]
Released in [v2.8.1](https://github.com/TwinProduction/gatus/releases/tag/v2.8.1)
