### ISSUE TITLE
Output version module

### ISSUE THREAD

**Issue by evsyukovaa** [TwinProduction/gatus#131]
Good day. I would like to be able to get the version of the module from curl
`<div>
             Version:
             <span class = "git"> 1.3.29.4 </span>
         </div>`
  or actuator from json
`"tags": "1.3.29.4",
"total": {
"commit": {
"count": "2959"
}
}`
From the instructions I realized that only conditional expressions ==, =>, <= ... is possible, but is it possible to simply display this string.
"[BODY] .Version {}"

**Comment by TwinProduction** [comment]
Hello @evsyukovaa :)

Just to make sure I understand, you want to expose the value at a JSONPath using a condition without evaluating it?

**Comment by evsyukovaa** [comment]
through jsonpath, most likely it will not work, there is probably another way to do this. But yes, I just want to be able to see on the status page which version is currently.

**Comment by TwinProduction** [comment]
The JSONPath used in the conditions is meant to be used strictly for testing, but if you really want, you can technically display it as long as you're satisfied with the service failing:
```yaml
services:
  - name: example
    url: "https://example.org/"
    conditions:
      - "[BODY].tags == whatever"
```

The above would technically show `[BODY].tags (1.3.29.4) == whatever` on the tooltip in the UI.

The reason for that is the condition results only display the value when it fail, which consequently means that the service fail.
![image](https://user-images.githubusercontent.com/15699766/125175339-768b0400-e199-11eb-8e6e-ed2f9b208414.png)

I doubt this is the outcome you're looking for, but currently, that's the only way to do it.

You could perhaps add a comment to #106 about adding that as well, but I think this may be a bit too specific as far as use cases go.

**Comment by evsyukovaa** [comment]
Thank you. It is strange that no one needed to see the expected result, which may be> or <of a known number, but simply show the value that is at the moment.

**Comment by TwinProduction** [comment]
Well, the idea is that the "conditions" on the UI are meant to be used as conditions for determining whether it a service is healthy or not, while what you're suggesting is purely informational 🤔

**Comment by TwinProduction** [comment]
I'm going to close this, because I think this is too much of an edge case. 
Placeholders were meant for evaluating services, not populating the UI. Populating the UI is just a side effect.

Sorry 😓
