### ISSUE TITLE
Reading database file

### ISSUE THREAD

**Issue by Meldiron** [TwinProduction/gatus#134]
Is it possible to use some software to read the database file that Gatus produces?
My config is:
```
storage:
  file: config/data.db
```

I have 900MB file but TablePlus (sql/mongo/sqlite/redis) database reader cannot read it. Any tips? What database technology does Gatus use?

**Comment by TwinProduction** [comment]
Hello @Meldiron 

Gatus uses https://github.com/TwinProduction/gocache, which does persistence with bbolt.
That said, there are plans to add support for databases like postgres and sqlite in the future.

**Comment by TwinProduction** [comment]
FYI, I've started working on a normalized schema for SQLite: #136.
Should be ready in a few days, or weeks at most.

**Comment by TwinProduction** [comment]
#136 has been pushed to the master branch, therefore, you should be able to test it out.
