### ISSUE TITLE
Response Time for metrics

### ISSUE THREAD

**Issue by sefaphlvn** [TwinProduction/gatus#142]
Hi all,

it be nice if the last response time values appears on the metrics page for all services

**Comment by TwinProduction** [comment]
That's definitely something I plan on implementing at some point.
In fact, it's one of the reasons I recently implemented #136. Next step will be adding support for a remote database like Postgres, and then Gatus will be able to persist as much data as it needs to, including the data necessary for having a calendar with the daily average response time over a long period of time.
