### ISSUE TITLE
Feature Request - Backend configuration via docker labels

### ISSUE THREAD

**Issue by dchidell** [TwinProduction/gatus#17]
Hello!

This might be a rather ambitious feature request, but I'll try my luck.

It would be great to have the ability to dynamically create monitored backends via labels within docker. Similar to how traefik uses labels to define backends for load balancing / content switching.

This would work by monitoring the docker socket for events, pulling the configuration out of labels and creating monitored backends dynamically from this information. The advantage of this is that configuration of gatus can be essentially static, and monitored configuration is applied per container.

By extension, this would allow additional status checks for docker based containers (i.e. is the container running or not). Any containers which cease to exist (i.e. deleted, not stopped) are removed from gatus' interface.

**Comment by dchidell** [comment]
If this is too large of a scope - I'd be happy to build an auxiliary service which writes the required yaml to config.yml and restarts gatus. However the issue with this approach is that history is lost when gatus is restarted. What would therefore be useful is to allow the re-reading of config.yml based on a signal (perhaps SIGHUP)?

**Comment by TwinProduction** [comment]
About reloading the configuration file, this is tracked in #29 

As for supporting backend configuration via docker labels, since this issue has been up for a while and has garnered no interest from other users, I won't be implementing it directly in Gatus, but you're free to create an auxiliary service as you suggested if you'd like.

**Comment by DragonHeart69** [comment]
@dchidell Have you create this ?

**Comment by dchidell** [comment]
I did actually, threw it together 4 years ago and have been using it ever since with no modification. It works fine for my needs, but probably wants some love and attention, I've pushed it here, hopefully there's enough there to get started: https://github.com/dchidell/gatus_docker_generator

**Comment by UtkarshVerma** [comment]
@TwiN would you be interested in a PR for this?

**Comment by TwiN** [comment]
@UtkarshVerma No, sorry. I think @dchidell 's approach of having this handled by an external application is a better approach.

**Comment by techgaud** [comment]
Inspired by dchidell’s approach, I decided to try my hand at something that worked better for my stack and workflow. It reads gatus.* labels off your containers and writes a Gatus config file into the directory Gatus already loads and hot-reloads. Automatically picks up labels, and drops the endpoint when you delete the container. Been running it on my own homelab for a while and it’s held up well. https://github.com/techgaud/autogatus
