### ISSUE TITLE
allow alert via webhook

### ISSUE THREAD

**Issue by undefined-moe** [TwinProduction/gatus#172]
e.g. POST https://xxxx.com/notify if service was down

**Comment by Histalek** [comment]
I think you are looking for [custom alerts](https://github.com/TwinProduction/gatus#configuring-custom-alerts)?

**Comment by undefined-moe** [comment]
Oh, thanks a lot. By the way, as endpoints like `api.telegram.org` was blocked in some region, is there a way to configure a proxy or custom endpoint?

**Comment by TwinProduction** [comment]
You can specify any endpoint you wish with `custom` alerts.

As for proxies, there's no such feature at the moment.
