### ISSUE TITLE
Security scanner complains on possbile SQL Injection

### ISSUE THREAD

**Issue by AndreiPaulau** [TwinProduction/gatus#180]
Hello,
The security scanner complains on SQL Injection.
Would you be so kind and tell us if this risk is relevant or not (and 'why' if possible).

Many thanks!

Here is the statement:

SQL injection may be possible.
--
Solution | Do not trust client side input, even if there is client side validation in place. In general, type check all data on the server side. If the application uses JDBC, use Prepared Statement or Callable Statement, with parameters passed by '?'If the application uses ASP, use ADO Command Objects with strong type checking and parameterized queries. If database Stored Procedures can be used, use them. Do *not* concatenate strings into queries in the stored procedure, or use 'exec', 'exec immediate', or equivalent functionality! Do not create dynamic SQL queries using simple string concatenation. Escape all data received from the client. Apply an 'allow list' of allowed characters, or a 'deny list' of disallowed characters in user input. Apply the principle of least privilege by using the least privileged database user possible. In particular, avoid using the 'sa' or 'db-owner' database users. This does not eliminate SQL injection, but minimizes its impact. Grant the minimum database access that is necessary for the application.
--
The original page results were successfully replicated using the expression [3-2] as the parameter value

The parameter value being modified was stripped from the HTML output for the purposes of the comparison
--
Attack 1: /api/v1/services/sites_some-site1/statuses?page=3-2
Attack 2: /api/v1/services/sites_some-site2/statuses?page=1+AND+1%3D1+--+

**Comment by TwinProduction** [comment]
Hello @AndreiPaulau,

It's actually not possible for a SQL injection to work here, since the `page` and `pageSize` parameters are explicitly converted to an `int`:
https://github.com/TwinProduction/gatus/blob/c57a930bf304a3f7e8088c7d0b6f699f6142de69/controller/handler/util.go#L21-L46

I believe that the reason your security scanner is picking this up is that rather than returning an error, if an invalid parameter is passed, the value is set to its default:
```go
page, err = strconv.Atoi(pageParameter)
if err != nil {
    page = DefaultPage
}
```
