### ISSUE TITLE
CERTIFICATE_EXPIRATION comparaison doesn't work as expected

### ISSUE THREAD

**Issue by Carlotronics** [TwinProduction/gatus#183]
Since my last contribution I did a few more tests about monitoring certificates expiration. I've just seen that `CERTIFICATE_EXPIRATION` comparaison doesn't fail when it should. For example, on target `https://example.org`, condition `[CERTIFICATE_EXPIRATION] > 90d` should fail because its certificate expires on December 26th, in 80 days.

For the time being I haven't had time to locate the code snippet that causes this but I plan to do this ASAP (this week-end hopefully).

Note to self: `CERTIFICATE_EXPIRATION` seems to be set to `6830765970` for `example.org`, which is approximately 1000*3600*24*80 (aka time before expiration, in ms).

**Comment by TwinProduction** [comment]
The unit `d` is not supported in Go.

Try to use `h` instead, e.g. `2160h` (90 days)
