### ISSUE TITLE
Uppercase SHA512 hash doesn't work

### ISSUE THREAD

**Issue by ocomsoft** [TwinProduction/gatus#21]
Thanks so much for adding this!

Not sure if I am doing this wrong BUT I just found that if I generate a SHA512 password and the alpha chars are uppercase it doesn't seem to work.. Maybe the code needs to convert it to lowercase when read from the config

Ie this didn't seem to work when I put it in the config:
BC547750B92797F955B36112CC9BDD5CDDF7D0862151D03A167ADA8995AA24A9AD24610B36A68BC02DA24141EE51670AEA13ED6469099A4453F335CB239DB5DA

Yes this did:
bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da

(the password here is "password1" ... safest password ever)

Hope that helps.

**Comment by TwinProduction** [comment]
😅 Good catch @ocomsoft

Resolved by 8fd6edd and released in [v1.3.1](https://github.com/TwinProduction/gatus/releases/tag/v1.3.1)
