### ISSUE TITLE
feature request: dynamic reload services config

### ISSUE THREAD

**Issue by mstrYoda** [TwinProduction/gatus#29]
It would be nice to reload services cfg. This enable us to dynamically create config from another source (like fetching services from consul and generating service config) and reload it via http api or some interval.

**Comment by Exagone313** [comment]
I think the right implementation would be with inotify (if available on the filesystem). Also, it needs to make sure that the new config doesn't have an error and keep previous config if it failed checks.

**Comment by TwinProduction** [comment]
@mstrYoda If you can, let me know if it works well for you.

**Comment by TwinProduction** [comment]
Released in [v2.6.0](https://github.com/TwinProduction/gatus/releases/tag/v2.6.0)
