### ISSUE TITLE
Alerting Custom URL Skip verifying the server's certificate chain and host name

### ISSUE THREAD

**Issue by ziedzaiem** [TwinProduction/gatus#31]
Hi !

I want to use a self hosted Mattermost for custom alerting notifications, unfortunately it does use an internal certificate authority not recognized by Gatus :
```
[watchdog][handleAlertsToTrigger] Ran into error sending an alert: Post "https://mattermost.****.***/hooks/hy3ajdg*****": x509: certificate signed by unknown authority
```

It would be nice to add an **insecure** option for **alerting.custom**.

Thank you for Gatus ! Easy to setup and configure, gets the job well done !

Best regards,

**Comment by TwinProduction** [comment]
Released in [v1.4.1](https://github.com/TwinProduction/gatus/releases/tag/v1.4.1)

**Comment by TwinProduction** [comment]
@ziedzaiem If you don't mind, would you let me know if the new feature works properly? I only briefly tested it, so a confirmation would be much appreciated :)

**Comment by ziedzaiem** [comment]
> @ziedzaiem If you don't mind, could you let me know if the new feature works properly? I only briefly tested it, so a confirmation would be much appreciated :)

Hi ! It works as expected ! Thank you very much :)
