### ISSUE TITLE
Extra comma at the end of the attachements array in Slack payload

### ISSUE THREAD

**Issue by ziedzaiem** [TwinProduction/gatus#34]
Hi !

There is an extra comma at the end of the array, it may cause parsing errors. Mattermost (Slack compatible) for example is rejecting the payload (400 HTTP Error).

https://github.com/TwinProduction/gatus/blob/79c60d834e6ca4f38dfac0bb996b6a6ff91946b5/alerting/provider/slack/slack.go#L58

Regards,

**Comment by TwinProduction** [comment]
Thank you for reporting this!
