### ISSUE TITLE
Support for human-readable duration comparison

### ISSUE THREAD

**Issue by Exagone313** [TwinProduction/gatus#39]
Some placeholders return durations, in milliseconds.

My proposal is to be able to compare durations with human-readable strings along with integers, such as `2 minutes` or `28 days`, which internally resolves to milliseconds.

The choice of supported formats is left for the implementation.

**Comment by Exagone313** [comment]
Related to #28

**Comment by Exagone313** [comment]
Oops, `interval` does support that. I might close that issue and update my PR for certificate expiration support.

**Comment by Exagone313** [comment]
I made a basic patch using `time.ParseDuration` in https://github.com/Exagone313/gatus/commit/c7aa01f8228283263b3cb2b69436759117e4e0ff (after certificate-expiration patches), but unfortunately it doesn't support days as per https://github.com/golang/go/issues/11473

**Comment by Exagone313** [comment]
@TwinProduction you can discuss my proposal here.

The thing missing is to implement strings such as `7d`, and add tests.

**Comment by TwinProduction** [comment]
Yeah, I'm thinking that we'll have to make a custom parse duration method that supports h and d

Everything else feels a bit too verbose

Honestly, I don't even think mixing them is necessary (i.e. 7d12h), just supporting 7d and 12h separately is sufficient
