### ISSUE TITLE
Configure bind address and port

### ISSUE THREAD

**Issue by Exagone313** [TwinProduction/gatus#40]
Currently, Gatus binds to `*:8080`:

https://github.com/TwinProduction/gatus/blob/d184786fd14e4e78aac519fc697357fdf8b180ca/main.go#L38-L40

While it is suitable for a container deployment, it may be desirable to, for example:
* bind on `localhost` to prevent direct access from the Internet (when running on the host),
* listen on another port if `8080` is already taken.

My proposal is to add an option for configuring address and port to bind to.

**Comment by TwinProduction** [comment]
Closed by #43

**Comment by TwinProduction** [comment]
Released in [v1.7.0](https://github.com/TwinProduction/gatus/releases/tag/v1.7.0)
