### ISSUE TITLE
Allow deployment on PaaS 

### ISSUE THREAD

**Issue by VincentHardouin** [TwinProduction/gatus#53]
# 🌮   Issue 
Hi, I would like to deploy this project on PaaS like [Heroku](https://www.heroku.com/home), but port is fixed. 

In PaaS, the application should use port provided by the environment variable. This is also a good practice given by [12 Factor](https://12factor.net/) methodology. 

# :robot:  Solution 

To solve this issue, i suggest a small modification as follow : 
```go
 port := os.Getenv("PORT")
 ret, err := strconv.Atoi(port)
 if err != nil {
   panic(fmt.Sprintf("port not provide"))
 }
```

Thanks, 
Regards

**Comment by TwinProduction** [comment]
Hello @VincentHardouin,

As of v1.7.0, Gatus now supports specifying a custom port by using the configuration file:

Here's an example:

```yaml
web:
  port: 8081

services:
  # ...
```

**Comment by VincentHardouin** [comment]
But with Heroku we don’t know the port in advance for example

**Comment by TwinProduction** [comment]
@VincentHardouin Ah I see.

You can use environment variables in the configuration file, like so:
```yaml
web:
  port: ${PORT}
```

Would that work?

**Comment by VincentHardouin** [comment]
I didn't know it was possible. It works great, thank you !

**Comment by denny64** [comment]
@VincentHardouin - do you have instructions on how to deploy on Heroku? Thanks

**Comment by VincentHardouin** [comment]
@denny64 yes i have explained this here : https://github.com/VincentHardouin/ING4-DevOps-Project#health-check
