### ISSUE TITLE
Exposing host http status as a prometheus metrics?

### ISSUE THREAD

**Issue by WilliamDahlen** [TwinProduction/gatus#6]
First of all, very good job! I was working on something like this aswell, but not as nice.

Have you thought about adding support for exporting the host http status as a prometheus metric? This would be so nice to have when using tools like grafana as you main source of monitoring.

Using a guage to toggle between 0 (offline/not 200-ok) and 1 (online/200-ok) can be enough to give value to a grafana dashboard and its alerting capabilities.

Again, solid work.

**Comment by WilliamDahlen** [comment]
Im just being stupid. you have done this already. nvm

**Comment by WilliamDahlen** [comment]
All my pride is gone, but the question still stands :1st_place_medal:

**Comment by xeruf** [comment]
What's up with this now?

**Comment by TwiN** [comment]
@xeruf https://github.com/TwiN/gatus#metrics 

The relevant metric is `gatus_results_code_total`.

You should be able to see an example in https://status.twin.sh/metrics
