### ISSUE TITLE
API

### ISSUE THREAD

**Issue by progressify** [TwinProduction/gatus#63]
there are some API for gatus?

**Comment by TwinProduction** [comment]
Well, there's one, but it's pretty much tailored to be used by Gatus' dashboard.

Here's an example: https://status.twinnation.org/api/v1/statuses

**Comment by TwinProduction** [comment]
The uptime during the last 1h, 24h and 7d will be exposed through the API soon.
See #62 

Closing this because the question has been answered.

**Comment by progressify** [comment]
thank you, that is good for now! :)
