### ISSUE TITLE
ICMP checks show connected on a host that is down

### ISSUE THREAD

**Issue by tertius** [TwinProduction/gatus#72]
I'm getting a check on connected for an ICMP but 0ms response time on a host that is down right now. Trying a manual ping from the docker host shows the same.

I've changed the condition to "[RESPONSE_TIME] > 0"

**Comment by TwinProduction** [comment]
@tertius What version of Gatus are you using?

**Comment by TwinProduction** [comment]
@tertius Thanks for reporting this, I was able to reproduce the issue.

I've pushed the fix to latest; if you could test it on your end to to make sure I didn't miss something, it'd be very appreciated.

**Comment by tertius** [comment]
Success, "[CONNECTED] == true" now works for a host that is down. It does show 5000ms, I'm assuming that's the timeout.

**Comment by TwinProduction** [comment]
@tertius That's correct.

Once again, thank you for creating an issue about this bug.

I've released this fix in [v1.11.2](https://github.com/TwinProduction/gatus/releases/tag/v1.11.2).
