### ISSUE TITLE
Support basic authentication for the dashboard

### ISSUE THREAD

**Issue by ocomsoft** [TwinProduction/gatus#8]
It would be good to be able to put a password on the dashboard page so I can secure it from being visible to everyone.

Great project. I was looking to write something similar myself but have not had time. Don't need to now.

**Comment by hurnhu** [comment]
If you are using proxy_pass with nginx you can do 

```
allow YOUR-IP;
deny all;
```

Of course this only works if you have a static IP. But is an easy way to restrict traffic. Anyone that isnt that IP will just get a 403 error

**Comment by ocomsoft** [comment]
Thanks but that doesn't work for me. We are not using nginx but also we have support staff all over the world so the list of IP addresses could be long.

**Comment by TwinProduction** [comment]
Released in [v1.3.0](https://github.com/TwinProduction/gatus/releases/tag/v1.3.0)
