### ISSUE TITLE
[Bug] Gatus doesn't respect system proxy

### ISSUE THREAD

**Issue by avakarev** [TwinProduction/gatus#86]
Go's standard client from `net/http` does support system proxy indicated by `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables (same as `curl`, `wget`, etc). Since `gatus` creates custom client's structs, the proxy option is missing, so it ignores available proxy. See `DefaultTransport`: https://golang.org/src/net/http/transport.go.

**Comment by TwinProduction** [comment]
Released in [v2.2.0](https://github.com/TwinProduction/gatus/releases/tag/v2.2.0)

**Comment by agermalid** [comment]
@TwiN in docker image: twinproduction/gatus:v3.6.0 HTTP_PROXY, HTTPS_PROXY environment variables ignores. At the same time, the curl command works through these variables - changed in Dockerfile FROM scratch to ubuntu and RUN apt update -y && apt install curl -y
