### ISSUE TITLE
Implement result history

### ISSUE THREAD

**Issue by arunmummidi** [TwinProduction/gatus#89]
At the moment, default span of health status is 2 hours. Is it possible to make it to 3 weeks? So, it will be more useful for historical view of health status for 3 weeks.

**Comment by TwinProduction** [comment]
Unlike other status pages/dashboards, Gatus has a configurable interval for each services monitored, so specifying a "oldest date" as a limit might be troublesome. 

For instance, a service with an interval of 30s would need 60480 entries to have enough for 3 weeks of history. Conversely, a service with an interval of 10m would need would only need 3024 entries.

The optimal approach would be to instead support up to X entries for each services regardless of their interval.

I already started setting up some ground work for this, in fact, it's one of the reason I recently migrated the project's front end to a decent framework, but I digress.

The main issue is that most of the status page solutions that have a kind of calendar which allows you to see the status from a few months ago are dumb in that what they check is very limited in scope (i.e. response time and status code) and they average them up for a day and represent that day with an uptime percentage or something similar.

While Gatus could do the same thing, it would be a lot more useful if the actual data was kept instead.

All that to say that I'm already looking into increasing the history kept, and the main challenge is to find a way to display the global dashboard between two dates while handling the fact that each services may have a different interval.

Paginating the results would be a lot simpler, but realistically speaking, the wider the gap between the interval of each services, the less aligned the services would be time-wise the further back you go, so pagination would really only be useful for the service detail page where it's not being compared to another service with a potentially different interval between each health check.

**Comment by TwinProduction** [comment]
Made a bit of progress on this yesterday night and this evening.

![image](https://user-images.githubusercontent.com/15699766/108934397-da61c580-761a-11eb-9d84-5a0d06cef6d8.png)
![image](https://user-images.githubusercontent.com/15699766/108934449-f1081c80-761a-11eb-8642-f67a5f4f751c.png)

I'm not making any promises yet; as I've mentioned in the comment above, there's a few challenges to tackle.
This is a very basic implementation, and to be frank, I'm not a big fan of it at the moment. I need to give it some more thoughts.

**Comment by TwinProduction** [comment]
Released in [v2.2.0](https://github.com/TwinProduction/gatus/releases/tag/v2.2.0)
