### ISSUE TITLE
Add ability to reload configuration file

### ISSUE THREAD

**Issue by dchidell** [TwinProduction/gatus#92]
I use a custom service which performs automated discovery for importing services into gatus.

The problem is there's no easy way to reload this configuration - I am currently just restarting the container, which works, but isn't a great solution.

It would be great to have some way to reload the config, perhaps either via a GET request to a particular endpoint, or a signal (SIGHUP?) to trigger a reload.

**Comment by TwinProduction** [comment]
Duplicate of #29
