### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by vijaydsk** [TwinProduction/gatus#94]
Hi Twin Productions,
Am planning to test the application. 
Please share me the installation document and prerequisites.
Thanks in advance

**Comment by TwinProduction** [comment]
Hello @vijaydsk, the installation instructions can be found on the repository's README, more specifically, you can test it out using the instructions given at https://github.com/TwinProduction/gatus#docker

You can also look at [these folders](https://github.com/TwinProduction/gatus/tree/master/example), which contain several examples using both Docker and Docker Compose.
