### ISSUE TITLE
ElasticSearch backend supports?

### ISSUE THREAD

**Issue by haruband** [TwinProduction/gatus#97]
Do you have some plan to support ElasticSearch backend?

I want to use ElasticSearch and Kibana for the health data from gatus.

Thank you!

**Comment by TwinProduction** [comment]
@haruband It's not off the table, but unless somebody else implements it, I have no plans to personally implement it in the very near future.
That said, if several people show their interest by 👍 the issue, I may prioritize this request over other tasks.

**Comment by TwinProduction** [comment]
Given how little support this has gathered over the past 4 months, I'm going to assume that this feature isn't interesting to many, and as such, I will close this.
